export const SET_AUTH = "SET_AUTH"
export const SET_ID = "SET_ID"
export const SET_USERNAME = "SET_USERNAME"
export const SET_PHONENUM = "SET_PHONENUM"
export const SET_EMAIL = "SET_EMAIL"
export const SET_TOKEN = "SET_TOKEN"