---- OPERATIONAL DB TABLES ----

USE DCMDB;

CREATE TABLE USER (
USER_ID INT,
USER_NAME VARCHAR(255), 
USER_PWD VARCHAR(255),
USER_EMAIL VARCHAR(255),
USER_MOBILE VARCHAR(50),
USER_POSTCODE SMALLINT,
USER_SEARCH_RDS VARCHAR(255),
USER_REG_DTTM DATETIME,
PRIMARY KEY (USER_ID)
);


CREATE TABLE USER_ORDER (
ORDER_ID VARCHAR(30),
USER_ID INT,
STORE_ID INT,
ORDER_TOTAL_PRICE DECIMAL(10,2),
ORDER_TOTAL_DISCOUNT DECIMAL(10,2),
ORDER_DTTM DATETIME,
PRIMARY KEY (ORDER_ID)
);


CREATE TABLE ORDER_ITEM (
ORDER_ID VARCHAR(30),
ITEM_ID INT,
ORDER_ITEM_QTY SMALLINT,
ORDER_ITEM_BASE_PRICE DECIMAL(8,2),
ORDER_ITEM_DISCOUNT_PRICE DECIMAL(8,2),
PRIMARY KEY (ORDER_ID, ITEM_ID, ORDER_ITEM_BASE_PRICE)
);


CREATE TABLE ITEM (
ITEM_ID INT,
CAT_ID INT,
ITEM_NAME VARCHAR(255),
ITEM_DESC VARCHAR(1000),
ITEM_WEIGHT VARCHAR(50),
ITEM_IMAGE_ID VARCHAR(10000),
PRIMARY KEY (ITEM_ID)
);


CREATE TABLE ITEM_PRICE_HIST (
ITEM_ID INT,
COM_ID INT,
IPH_DATE DATE,
IPH_ITEM_BASE_PRICE DECIMAL(8,2),
IPH_ITEM_DISCOUNT_PRICE DECIMAL(8,2),
IPH_ITEM_DISCOUNT_PCT DECIMAL(4,2),
PRIMARY KEY (ITEM_ID, COM_ID, IPH_DATE)
);


CREATE TABLE ITEM_PRICE_CURRENT (
ITEM_ID INT,
COM_ID INT,
IP_ITEM_BASE_PRICE DECIMAL(8,2),
IP_ITEM_DISCOUNT_PRICE DECIMAL(8,2),
IP_ITEM_DISCOUNT_PCT DECIMAL(4,2),
IP_FOUR_WK_HIGHEST_PRICE DECIMAL(8,2),
IP_FOUR_WK_LOWEST_PRICE DECIMAL(8,2),
PRIMARY KEY (ITEM_ID, COM_ID)
);


CREATE TABLE ITEM_PRICE_PREDICTION (
ITEM_ID INT,
COM_ID INT,
IPP_NEXT_WK_DISCOUNT_PBTY DECIMAL(5,4),
IPP_NEXT_WK_DISCOUNT_PRICE DECIMAL(8,2),
PRIMARY KEY (ITEM_ID)
);


CREATE TABLE STORE (
STORE_ID INT,
COM_ID INT,
STORE_POSTCODE SMALLINT,
STORE_ADDRESS VARCHAR(255),
STORE_GPS VARCHAR(255),
STORE_NAME VARCHAR(255),
PRIMARY KEY (STORE_ID)
);


CREATE TABLE COMPANY (
COM_ID INT,
COM_NAME VARCHAR(255),
PRIMARY KEY (COM_ID)
);


CREATE TABLE USER_ITEM_CART (
USER_ID INT,
ITEM_ID INT,
PRIMARY KEY (USER_ID, ITEM_ID)
);


CREATE TABLE CATEGORY (
CAT_ID INT,
CAT_NAME VARCHAR(255),
PRIMARY KEY (CAT_ID)
);


CREATE TABLE RECOMMEND_ITEM (
USER_ID INT,
ITEM_ID INT,
COM_ID INT,
PRIMARY KEY (USER_ID,ITEM_ID,COM_ID)
);


CREATE TABLE ITEM_IMAGE (
  ITEM_IMAGE_ID INT ,
  IMAGE TEXT,
  PRIMARY KEY (ITEM_IMAGE_ID)
);


CREATE TABLE STG_TRANSACTION (
TXN_DATE VARCHAR(255),
TXN_SUBURB VARCHAR(255),
TXN_ADDRESS VARCHAR(255),
TXN_INVOICE_NUM VARCHAR(255),
TXN_ITEM_DESC VARCHAR(255),
TXN_ITEM_UNIT_PRICE VARCHAR(255),
TXN_ITEM_PRICE VARCHAR(255)
);


CREATE TABLE STG_TRANSACTION_ITEM_ID (
ITEM_ID INT,
ITEM_NAME VARCHAR(255)
);


---- ANALYTIC DB TABLES ----

CREATE TABLE STAGING_WOOLY_ITEM_PRICE (
WOOLY_PRICE_DATE VARCHAR(255),
WOOLY_ITEM_CODE VARCHAR(255),
WOOLY_ITEM_NAME VARCHAR(255),
WOOLY_ITEM_PRICE VARCHAR(255)
);



CREATE TABLE STAGING_COLES_ITEM_PRICE (
COLES_PRICE_DATE DATE,
COLES_ITEM_NAME VARCHAR(255),
COLES_ITEM_PRICE VARCHAR(255),
COLES_ITEM_UNIT_PRICE VARCHAR(255)
);


CREATE TABLE ODS_COLES_ITEM_PRICE (
COLES_PRICE_DATE DATE,
COLES_ITEM_NAME VARCHAR(255),
COLES_ITEM_PRICE DECIMAL(8,2),
COLES_ITEM_UNIT_PRICE VARCHAR(255)
);


CREATE TABLE WEEKLY_ITEM_PRICE (
COM_ID INT,
WKY_PRICE_DATE DATE,
WKY_ITEM_CODE INT,
WKY_ITEM_NAME VARCHAR(255),
WKY_ITEM_PRICE DECIMAL(8,2),
PRIMARY KEY (COM_ID,WKY_PRICE_DATE,WKY_ITEM_CODE)
);
